language: android

android:
  components:
  - build-tools-21.1.2
  licenses:
    - android-sdk-license-5be876d5
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x android-wait-for-emulator
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script: "./gradlew clean assembleDebug -x connectedAndroidTest"

deploy:
  provider: s3
  local-dir: AdHoc-Railway/build/outputs/apk/
  access_key_id: AKIAJA4QRNGVXSMAEBDA
  secret_access_key:
    secure: kjn7R44vhIxxezl8O8IUQN0bOPlaJX/lRwAn55EmhsrHIYvfdE5dDoyYFKPvT1HysfDdKG9xr1SKL+pqQh9xhQ4VLiA8RMkx0Jn01Dch1YXRhW6R+NEnUiVDBHjcBN+XihhB1/foMZkn0DNojWAxbyOlAW03pN3sFODxgy8433E=
  bucket: AdHoc-Railway
  on:
    branch: develop
    repo: forkch/adhoc-railway-android